lib/backend_web/router.ex
defmodule BackendWeb.Router do
  use BackendWeb, :router
  import Phoenix.LiveDashboard.Router
  import Plug.BasicAuth
  alias BackendWeb.LivePlug.AssignDefaults
  alias BackendWeb.LivePlug.AdminAuth
  use ErrorTracker.Web, :router
  use Kaffy.Routes, scope: "/admin/kaffy", pipe_through: [:auth, :kaffy_admin]

  pipeline :auth do
    plug(Backend.UserManager.Pipeline)
  end

  pipeline :kaffy_admin do
    plug(Backend.Plug.AdminAuth, role: :kaffy)
  end

  pipeline :super_admin do
    plug(Backend.Plug.AdminAuth, role: :super)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  forward("/api/graphql", Absinthe.Plug, schema: BackendWeb.Schema)

  forward("/graphiql", Absinthe.Plug.GraphiQL,
    schema: BackendWeb.Schema,
    interface: :playground
  )

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:put_root_layout, {BackendWeb.LayoutView, :root})
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  # defp api_auth(conn, _opts) do
  #   with {user, pass} <- Plug.BasicAuth.parse_basic_auth(conn),
  #        {:ok, api_user} <- Backend.Api.verify_user(user, pass) do
  #     assign(conn, :api_user, api_user)
  #   else
  #     _ -> conn |> Plug.BasicAuth.request_basic_auth() |> halt()
  #   end
  # end

  pipeline :admins_only do
    plug(:basic_auth,
      username: "admin",
      password: Application.compile_env!(:backend, :admin_pass)
    )
  end

  scope "/api/public", BackendWeb do
    pipe_through([:api])
    post("/dt/game", DeckTrackerController, :put_game)
    put("/dt/game", DeckTrackerController, :put_game)
    get("/log", PageController, :log)
    post("/log", PageController, :log)
    put("/log", PageController, :log)

    post("/patreon/webhook", PatreonController, :webhook)
  end

  scope "/api", BackendWeb do
    pipe_through([:api])
    post("/deck-info", DeckController, :deck_info)
    get("/deck-info/*deck", DeckController, :deck_info)
    get("/who-am-i", ApiController, :who_am_i)
    post("/dt/game", DeckTrackerController, :put_game)
    put("/dt/game", DeckTrackerController, :put_game)
    get("/cards/dust-free", CardsController, :dust_free)
    get("/cards/all", CardsController, :all)
    get("/cards/collectible", CardsController, :collectible)
    get("/cards/metadata", CardsController, :metadata)
  end

  scope "/admin", BackendWeb do
    pipe_through([:browser, :auth, :super_admin])
    live("/panel", AdminPanelLive)
    live("/super/playground", PlaygroundLive)
  end

  scope "/", BackendWeb do
    pipe_through([:browser, :auth])

    get("/arcticles/reveal/booms-incredible-inventions-mage", RevealController, :boom)
    get("/hs/article/:blog_id", HearthstoneController, :article)
    get("/battlefy/tournament/020fface81eb7119705c0df5:bla", PageController, :rick_astley)

    get("/leaderboard", LeaderboardController, :index)
    get("/leaderboard/player-stats", LeaderboardController, :player_stats)

    get(
      "/leaderboard/player-history/region/:region/period/:period/leaderboard_id/:leaderboard_id/player/:player",
      LeaderboardController,
      :player_history
    )

    get(
      "/leaderboard/rank-history/region/:region/period/:period/leaderboard_id/:leaderboard_id/rank/:rank",
      LeaderboardController,
      :rank_history
    )

    get(
      "/leaderboard/player-history/region/:region/season_id/:season_id/leaderboard_id/:leaderboard_id/player/:player",
      LeaderboardController,
      :player_history_old
    )

    get("/leaderboard/points", LeaderboardController, :points)

    live("/", FeedLive)
    get("/incubator", PageController, :incubator)
    get("/about", PageController, :about)
    get("/donate-follow", PageController, :donate_follow)
    get("/privacy", PageController, :privacy)

    get("/hdt-plugin", PageController, :hdt_plugin)

    get("/log", PageController, :log)
    put("/log", PageController, :log)
    post("/log", PageController, :log)

    get("/test", PageController, :test)

    get("/hs/patch-notes", HearthstoneController, :patch_notes)
    get("/hs/patchnotes", HearthstoneController, :patch_notes)

    live("/legacy-hsesports", LegacyHSEsportsLive)
    get("/legacy-hsesports/invited/:tour_stop", MastersTourController, :invited_players)
    get("/legacy-hseports/invited/", MastersTourController, :invited_players)
    get("/legacy-hsesports/qualifiers", MastersTourController, :qualifiers)
    get("/legacy-hsesports/mt/points", MastersTourController, :points)
    get("/legacy-hsesports/mt/earnings", MastersTourController, :earnings)
    get("/legacy-hsesports/mt/qualifier-stats/", MastersTourController, :qualifier_stats)

    get(
      "/legacy-hsesports/mt/qualifier-stats/:tour_stop",
      MastersTourController,
      :qualifier_stats
    )

    get("/mt/tour-stops", MastersTourController, :tour_stops)
    get("/legacy-hsesports/mt/stats", MastersTourController, :masters_tours_stats)
    get("/mtq/:mtq_num", MastersTourController, :qualifier_redirect)
    get("/mtq/:mtq_num/*rest", MastersTourController, :qualifier_redirect)

    get("/hdt-plugin/latest-version", DeckTrackerController, :hdt_plugin_latest_version)
    get("/hdt-plugin/latest", DeckTrackerController, :hdt_plugin_latest_file)
    get("/hdt-plugin/d0nkey.top plugin.dll", DeckTrackerController, :hdt_plugin_latest_file)

    get(
      "/battlefy/third-party-tournaments/stats/:stats_slug",
      BattlefyController,
      :organization_tournament_stats
    )

    get("/battlefy/third-party-tournaments", BattlefyController, :organization_tournaments)

    live("/battlefy/tournament/:tournament_id/match/:match_id", BattlefyMatchLive)
    live("/battlefy/tournament/:tournament_id/lineups", BattlefyTournamentDecksLive)
    live("/battlefy/tournament/:tournament_id/participants", BattlefyParticipantsLive)

    get("/profile/battlefy/tournament/:tournament_id", BattlefyController, :profile_tournament)
    get("/battlefy/tournament/:tournament_id", BattlefyController, :tournament)

    get(
      "/battlefy/tournament/:tournament_id/player/:team_name",
      BattlefyController,
      :tournament_player
    )

    get(
      "/battlefy/tournament/:tournament_id/future/:team_name",
      BattlefyController,
      :tournament_player
    )

    get(
      "/battlefy/tournament/:tournament_id/decks/:team_name",
      BattlefyController,
      :tournament_decks
    )

    get(
      "/battlefy/tournaments-stats/",
      BattlefyController,
      :tournaments_stats
    )

    get("/battlefy/user-tournaments/:slug", BattlefyController, :user_tournaments)

    get("/hsreplay/matchups", HSReplayController, :matchups)

    get("/discord/broadcasts", DiscordController, :broadcasts)

    # get "/discord/broadcast", DiscordController, :broadcast
    # post "/discord/broadcast", DiscordController, :broadcast

    get("/discord/broadcasts/:id/publish/:token", DiscordController, :view_publish)
    post("/discord/broadcasts/:id/publish/:token", DiscordController, :publish)

    get("/discord/broadcasts/:id/subscribe/:token", DiscordController, :view_subscribe)
    post("/discord/broadcasts/:id/subscribe/:token", DiscordController, :subscribe)

    get("/discord/create_broadcast", DiscordController, :create_broadcast)

    get("/player-profile/:battletag_full", PlayerController, :player_profile)

    get("/streamer-decks/twitch-login/:twitch_login", StreamingController, :streamers_decks)
    get("/streamer-decks", StreamingController, :streamer_decks)
    get("/streamer-instructions", StreamingController, :streamer_instructions)
    live("/streaming-now", StreamingNowLive)
    live("/youtube/bnet-chat/:video_id", YoutubeChatLive)

    live("/cards", CardsLive)
    live("/card/:card_id", CardLive)

    live("/deckbuilder", DeckBuilderLive)
    live("/deckviewer", DeckviewerLive)

    get("/stats/explanation", StatsController, :explanation)
    live("/esports", EsportsLive)
    live("/card-stats", CardStatsLive)
    live("/meta", MetaLive)
    live("/decks", DecksLive)
    live("/deck-sheets/:sheet_id", DeckSheetViewLive)
    live("/deck-sheets", DeckSheetsIndexLive)
    live("/replays", ReplaysLive)

    live("/archetype/:archetype", ArchetypeLive)

    live("/hcm-2022", HCM2022Live)
    live("/lineup-history/:source/:name", LineupHistoryLive)

    # get "/decks", PageController, :disabled
    live("/deck/*deck", DeckLive)
    live("/deck-tracker/*deck", DeckTrackerLive)

    get("/grandmasters/season/:season", GrandmastersController, :grandmasters_season)

    get("/who-am-i", AuthController, :who_am_i)
    get("/whoami", AuthController, :who_am_i)
    get("/login-welcome", AuthController, :login_welcome)
    get("/logout", AuthController, :logout)
    live("/feed", FeedLive)
    get("/empty/with-nav", EmptyController, :with_nav)
    get("/empty/without-nav", EmptyController, :without_nav)

    live("/fantasy", FantasyIndexLive)
    live("/fantasy/leagues/:league_id/draft", FantasyDraftLive)
    live("/fantasy/leagues/:league_id", FantasyLeagueLive)
    live("/fantasy/leagues/join/:join_code", JoinLeagueLive)

    get("/util/twitter/callback/reqtop100", TwitterController, :req_top100_callback)

    get("/discord-bot", SocialController, :discord_bot)
    get("/discord_bot", SocialController, :discord_bot)
    get("/discord", SocialController, :discord)
    get("/paypal", SocialController, :paypal)
    get("/twitch", SocialController, :twitch)
    get("/patreon", SocialController, :patreon)
    get("/twitter", SocialController, :twitter)
    get("/notion", SocialController, :notion)
    get("/liberapay", SocialController, :liberapay)

    live("/gm/lineups", GrandmastersLineup)
    live("/gm", GrandmastersLive)
    live("/gm/profile/:gm", GrandmasterProfileLive)

    live(
      "/tournament-lineups/:tournament_source/:tournament_id/popularity",
      TournamentLineupPopularityTableLive
    )

    live(

lib/backend_web/views/layout_view.ex
defmodule BackendWeb.LayoutView do
  use BackendWeb, :view
  import FunctionComponents.LayoutComponent

  def current_mt(conn) do
    case Backend.MastersTour.TourStop.get_current() do
      nil -> ""
      ts -> show_mt(conn, ts)
    end

    #    today = Date.utc_today()
    #
    #    case {today.year, today.month, today.day} do
    #      {2020, 6, day} when day > 11 and day < 18 -> show_mt(conn, :"Jönköping")
    #      _ -> ""
    #    end
  end

  def render_battlefy_link(assigns) do
    ~H"""
    """
  end

  def show_mt(conn, tour_stop) do
    case Backend.Battlefy.get_tour_stop_id(tour_stop) do
      {:error, _} ->
        ""

      {:ok, id} ->
        name =
          case Backend.MastersTour.TourStop.get(tour_stop) do
            %{display_name: dn} when is_binary(dn) -> dn
            %{id: id} -> id
            _ -> tour_stop
          end

        assigns = %{conn: conn, name: name, id: id}

        ~H"""
          <a class="navbar-item" href={Routes.battlefy_path(@conn, :tournament, @id)}><%= @name %> </a>
        """
    end
  end

  def grandmasters(conn) do
    link = Routes.grandmasters_path(conn, :grandmasters_season, "2020_2")

    assigns = %{link: link}

    ~H"""
      <a class="navbar-item" href={@link}>Grandmasters</a>
    """
  end

  def render("navbar.html", %{handle_user: true, conn: conn}) do
    user =
      conn
      |> Guardian.Plug.current_resource()
      |> case do
        %{battletag: bt} -> bt
        _ -> nil
      end

    render("navbar.html", %{user: user, conn: conn})
  end

  def current_dreamhack(%Plug.Conn{} = _conn) do
    case Dreamhack.current() do
      current = [_ | _] ->
        current_dreamhack(%{current: current})

      _ ->
        ""
    end
  end

  def current_dreamhack(assigns) do
    ~H"""
      <div class="navbar-item has-dropdown is-hoverable">
        <div class="navbar-link">
          DreamHack
        </div>

        <div class="navbar-dropdown">
          <%= for {tour, id} <- @current do %>
            <a class="navbar-item" href={~p"/battlefy/tournament/#{id}"}>
              <%= tour %>
            </a>
          <% end %>
        </div>
      </div>
    """
  end

  def show_lobby_legends?() do
    Backend.LobbyLegends.LobbyLegendsSeason.current(1, 48)
  end

  def show_fantasy?() do
    false &&
      (ongoing_dreamhack_fantasy?() ||
         ongoing_mt_fantasy?() ||
         ongoing_lobby_legends_fantasy?() ||
         highlight_fantasy_for_gm?())
  end

  @spec battlefy?(Backend.UserManager.User.t() | nil) :: boolean()
  def battlefy?(%{battlefy_slug: slug}) when is_binary(slug), do: true
  def battlefy?(_), do: false

  def twitchbot?(user) do
    with %{twitch_id: twitch_id} when not is_nil(twitch_id) <- user,
         %{twitch_login: twitch_login} <- Backend.Streaming.streamer_by_twitch_id(twitch_id),
         chats <- Application.get_env(:backend, :twitch_bot_chats) do
      twitch_login in chats
    else
      _ -> false
    end
  end

  defp ongoing_lobby_legends_fantasy?(),
    do: !!Backend.LobbyLegends.LobbyLegendsSeason.current(120, 60)

  defp ongoing_mt_fantasy?(), do: !!Backend.MastersTour.TourStop.get_current(120, 60)
  defp ongoing_dreamhack_fantasy?(), do: Enum.any?(Dreamhack.current_fantasy())
  defp highlight_fantasy_for_gm?(), do: false

  @spec enable_nitropay?(Plug.Conn.t()) :: boolean
  def enable_nitropay?(%{params: %{"nitropay_test" => "yes"}}), do: true
  def enable_nitropay?(_), do: Application.get_env(:backend, :enable_nitropay, false)

  @spec enable_adsense?(Plug.Conn.t()) :: boolean
  def enable_adsense?(conn) do
    Backend.AdsTxtCache.config()
    |> Enum.find_value(false, fn {host, %{enable_adsense: enable}} ->
      conn.host =~ host && enable
    end)
  end

  @spec hide_ads?(Plug.Conn.t()) :: boolean
  def hide_ads?(conn) do
    conn
    |> user()
    |> Backend.UserManager.User.hide_ads?()
  end

  @spec show_ads?(Plug.Conn.t()) :: boolean
  def show_ads?(conn), do: !hide_ads?(conn)

  @spec space_for_ads?(Plug.Conn.t()) :: boolean
  def space_for_ads?(conn), do: enable_nitropay?(conn) && show_ads?(conn)

  def container_classes(conn) do
    if enable_nitropay?(conn) && show_ads?(conn) do
      "container is-fluid space-for-ads"
    else
      "container is-fluid"
    end
  end

  def nitropay_demo?() do
    Application.get_env(:backend, :nitropay_demo, true)
  end
end

lib/backend_web/templates/layout/ads_all.html.eex
<script>
    window['nitroAds'].createAd('responsive-anchor-phone', {
    "refreshLimit": 10,
    "refreshTime": 90,
    "format": "anchor",
    "anchor": "bottom",
    "demo": <%= nitropay_demo?() %>,
    "anchorPersistClose": false,
    "sizes": [],
    "report": {
        "enabled": true,
        "wording": "Report Ad",
        "position": "top-right"
    },
    "mediaQuery": "(min-width: 768px) and (max-width: 1024px), (min-width: 320px) and (max-width: 767px)"
    });
  window["nitroAds"].createAd("nitropay-sticky-stack", {
    format: "sticky-stack",
    stickyStackLimit: 15,
    stickyStackSpace: 2.5,
    demo: <%= nitropay_demo?() %>,
    stickyStackOffset: 20,
    report: {
      enabled: true,
      wording: "Report Ad",
      position: "fixed-bottom-right"
    }
  });
</script>
<script>
window['nitroAds'].createAd('nitropay-below-title-leaderboard', {
  "refreshLimit": 10,
  "refreshTime": 60,
  "renderVisibleOnly": true,
  "refreshVisibleOnly": true,
  demo: <%= nitropay_demo?() %>,
  "sizes": [
    [
      "728",
      "90"
    ],
    [
      "970",
      "90"
    ]
  ],
  "report": {
    "enabled": true,
    "wording": "Report Ad",
    "position": "top-right"
  },
  "mediaQuery": "(min-width: 1025px), (min-width: 768px) and (max-width: 1024px)"
});
</script>
<script>
window['nitroAds'].createAd('nitropay-interstitial', {
  "format": "interstitial",
  "demo": <%= nitropay_demo?() %>,
  "mediaQuery": "(min-width: 320px) and (max-width: 767px)"
});
</script>

lib/backend_web/templates/layout/app.html.eex
<!DOCTYPE html>
<!-- app.html.eex -->
<div>
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <%= @inner_content %>
</div>

lib/backend_web/templates/layout/app.html.heex
<!DOCTYPE html>
<!-- app.html.eex -->
<div>
    <p class="alert alert-info" role="alert"><%= Phoenix.Flash.get(@flash, :info)  %></p>
    <p class="alert alert-danger" role="alert"><%= Phoenix.Flash.get(@flash, :error) %></p>
    <%= @inner_content %>
</div>

lib/backend_web/templates/layout/live.html.leex
<!-- live.html.leex -->
<div>
    <p><%= live_flash(@flash, :notice) %></p>
    <p><%= live_flash(@flash, :error) %></p>
    <%= @inner_content %>
</div>

lib/backend_web/templates/layout/navbar.html.heex
<!-- template: navbar.html.eex -->

 <nav id="main-navbar" class="navbar is-dark" role="navigation" aria-label="main navigation" style="display:none">
   <div class="navbar-brand">
     <a class="navbar-item" aria-lebal="menu-item" href="/"><img src={Application.fetch_env!(:backend, :favicon)} alt="HSGuru"></a>

     <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="burger-toggle">
       <span aria-hidden="true"></span>
       <span aria-hidden="true"></span>
       <span aria-hidden="true"></span>
     </a>
   </div>

   <div id="burger-toggle" class="navbar-menu">
     <div class="navbar-start">
        <%= if @user do %>
          <.navbar_dropdown display={@user}>
            <.navbar_item_link link={~p"/player-profile/#{@user}"} display={"Player Profile"} />
            <.navbar_item_link link={~p"/deck-sheets"} display={"Deck Sheets"} />
            <.navbar_item_link link={~p"/my-decks"} display={"My Decks"} />
            <.navbar_item_link link={~p"/my-replays"} display={"My Replays"} />
            <.navbar_item_link link={~p"/my-groups"} display={"My Groups"} />
            <%= if @conn |> user() |> battlefy?() do %>
              <.navbar_item_link link={~p"/battlefy/user-tournaments/#{user(@conn).battlefy_slug}"} display="My Battlefy Tournaments" />
            <% end %>
            <%= if @conn |> user() |> twitchbot?() do %>
              <.navbar_item_link link={~p"/twitch/bot"} display={"My Twitch Bot"} />
            <% end %>
            <.navbar_item_link link={~p"/profile/settings"} display={"Settings"} />
            <%= if can_access?(@conn, :battletag_info) do %>
              <.navbar_item_link link={~p"/torch/battletag_info"} display={"Admin - Battletag Info"} />
            <% end %>
            <%= if can_access?(@conn, :periods) do %>
              <.navbar_item_link link={~p"/torch/periods"} display={"Admin - Periods"} />
            <% end %>
            <%= if can_access?(@conn, :kaffy) do %>
              <.navbar_item_link link={~p"/dashboard"} display={"Dashboard"} />
              <.navbar_item_link link={~p"/admin/panel"} display={"Admin Panel"} />
              <.navbar_item_link link={~p"/admin/kaffy"} display={"Kaffy"} />
            <% end %>
            <.navbar_item_link link={~p"/logout"} display={"Logout"} />
            <%= if can_access?(@conn, :developer) do %>
              <% query_part = if @conn.query_string != "", do: "?#{@conn.query_string}", else: "" %>
              <.navbar_item_link link={"http://localhost:8994" <> @conn.request_path <> query_part} display={"Localhost"} />
              <.navbar_item_link link={"https://localdev.hsguru.com" <> @conn.request_path <> query_part} display={"Localdev"} />
              <.navbar_item_link link={"https://staging.hsguru.com" <> @conn.request_path  <> query_part} display={"Staging"} />
              <.navbar_item_link link={"https://www.hsguru.com" <> @conn.request_path  <> query_part} display={"Production"} />
            <% end %>
          </.navbar_dropdown>
        <% else %>
          <.navbar_dropdown display={"👤"}>
            <.navbar_item_link link={~p"/auth/bnet"} display="Sign in (Battlenet)"/>
          </.navbar_dropdown>
        <% end %>
        <.navbar_dropdown display="Leaderboards" main_link={~p"/leaderboard"}>
          <.navbar_item_link link={~p"/leaderboard/player-stats"} display={"Player Stats"} />
          <.navbar_item_link link={~p"/leaderboard/points"} display={"HSEsports Points"} />
          <%= for {region, region_name} <- Backend.Blizzard.regions_with_name() do %>
            <.navbar_item_link link={~p"/leaderboard?#{%{region: region}}"} display={region_name} />
          <% end %>
        </.navbar_dropdown>

        <.navbar_dropdown display="Decks" main_link={~p"/decks"}>
          <.navbar_item_link link={~p"/decks?format=2"} display={"Standard"} />
          <.navbar_item_link link={~p"/decks?format=1"} display={"Wild"} />
          <.navbar_item_link link={~p"/decks?format=4"} display={"Twist"} />
        </.navbar_dropdown>
        <.navbar_dropdown display="Meta" main_link={~p"/meta"}>
          <.navbar_item_link link={~p"/meta?format=2"} display={"Standard"} />
          <.navbar_item_link link={~p"/meta?format=1"} display={"Wild"} />
          <.navbar_item_link link={~p"/meta?format=4"} display={"Twist"} />
        </.navbar_dropdown>
        <.navbar_item_link link={~p"/streamer-decks"} display={"Streamer Decks"}/>
        <.navbar_item_link link={~p"/esports"}>Esports</.navbar_item_link>
        <.navbar_dropdown display="Utilities">
          <.navbar_item_link link={~p"/deckviewer"} display={"Deckviewer"} />
          <.navbar_item_link link={~p"/deckbuilder"} display={"Deckbuilder"} />
          <.navbar_item_link link={~p"/cards"} display={"Cards"} />
        </.navbar_dropdown>
        <.navbar_dropdown display="Misc">
          <.navbar_item_link link={~p"/legacy-hsesports"} display={"Legacy HSEsports"} />
          <.navbar_item_link link={~p"/replays"} display={"Replays"} />
          <.navbar_item_link link={~p"/battlefy/third-party-tournaments"} display={"3rd Party Tournaments"} />
          <.navbar_item_link link={~p"/battlefy/tournaments-stats"} display={"Battlefy Tournament Stats"} />
          <.navbar_item_link link={~p"/streaming-now"} display={"Streaming Now"} />
          <.navbar_item_link link={~p"/fantasy"} display={"Fantasy"} />
          <.navbar_item_link link={~p"/discord-bot"} display={"Discord Bot"} />
          <.navbar_item_link link={~p"/hdt-plugin"} display={"HDT Plugin"} />
          <.navbar_item_link link={~p"/about"} display={"About"} />
        </.navbar_dropdown>
        <.live_battlefy 
          display={"Solary"} 
          start={~N[2024-08-10 12:00:00]}
          finish={~N[2024-08-12 23:30:00]}
          battlefy_id={"66b63b2faedcd30040d11241"}
          twitch={"solaryhs"}
        />

        <.live_battlefy 
          display={"Worlds"} 
          start={~N[2023-12-15 17:00:00]} 
          finish={~N[2023-12-20 05:30:00]} 
          battlefy_id={"6578b996b94cda278bb85cca"}
          twitch={"playhearthstone"}
        />

        <.live_battlefy 
          display={"Worlds"} 
          start={~N[2024-12-12 20:00:00]} 
          finish={~N[2024-12-20 05:30:00]} 
          battlefy_id={"674fa20b0d896f0018364671"}
          twitch={"playhearthstone"}
        />

      <a class="navbar-item" :if={NaiveDateTime.compare(NaiveDateTime.utc_now(), ~N[2024-11-18 12:12:00]) == :lt} href={~p"/wc/2024/china-qualifiers"}>CN Worlds Qual</a>
       <%= current_mt @conn %>

       <%= current_dreamhack @conn %>
     </div>

     <div class="navbar-end">
      <div :if={NaiveDateTime.compare(NaiveDateTime.utc_now(), ~N[2024-05-14T00:00:00]) == :gt and show_ads?(@conn)} class="navbar-item" aria-label="menu-item">
        <span class="is-hidden-mobile">
          Remove ads by supporting
        </span>
        <Components.Socials.patreon link={~p"/patreon"} />
      </div>
      <div :if={NaiveDateTime.compare(NaiveDateTime.utc_now(), ~N[2024-05-14T00:00:00]) == :lt} class="navbar-item" aria-label="menu-item">
        <a :if={Backend.Reveals.show?(:boom, @user)} class="column is-narrow" href={~p"/arcticles/reveal/booms-incredible-inventions-mage"}>
          <article class="media">
            <div class="media-content">
              <span class="title is-5">Miniset Mage Reveals!</span>
            </div>
          </article>
        </a>
      </div>
     </div>
   </div>
 </nav>
<script>
   var navbar = document.getElementById('main-navbar');
   if (navbar) {
   navbar.style.display = '';
   } else {
       conyole.log("Couldn't get navbar!")
   }

document.addEventListener('DOMContentLoaded', () => {

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {

        // Get the target from the "data-target" attribute
        const target = el.dataset.target;
        const $target = document.getElementById(target);

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});
</script>
<noscript>
  <header class="container">
    <nav role="navigation">
      <a href="/">🏠</a>
      <a href={"#{Routes.leaderboard_path(@conn, :index)}"}>Leaderboard</a>
      |
      <a href={~p"/esports"}>Esports</a>
      |
      <a href={"#{Routes.live_path(@conn, BackendWeb.DecksLive) }"}>Decks</a>
      |
      <a href={"#{Routes.streaming_path(@conn, :streamer_decks) }"}>Streamer Decks</a>
      |
      <a href={"#{Routes.page_path(@conn, :donate_follow)}"}>Donate/Follow</a>
      | 
      <a href={~p"/meta"}>Meta</a>
      |
    </nav>
  </header>
</noscript>