lib/backend_web/router.ex
    plug(:put_root_layout, {BackendWeb.LayoutView, :root})
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  # defp api_auth(conn, _opts) do
  #   with {user, pass} <- Plug.BasicAuth.parse_basic_auth(conn),
  #        {:ok, api_user} <- Backend.Api.verify_user(user, pass) do
  #     assign(conn, :api_user, api_user)
  #   else
  #     _ -> conn |> Plug.BasicAuth.request_basic_auth() |> halt()
  #   end
  # end

  pipeline :admins_only do
    plug(:basic_auth,
      username: "admin",
      password: Application.compile_env!(:backend, :admin_pass)
    )
  end

  scope "/api/public", BackendWeb do
    pipe_through([:api])
    post("/dt/game", DeckTrackerController, :put_game)
    put("/dt/game", DeckTrackerController, :put_game)
    get("/log", PageController, :log)
    post("/log", PageController, :log)
    put("/log", PageController, :log)

    post("/patreon/webhook", PatreonController, :webhook)
  end

  scope "/api", BackendWeb do
    pipe_through([:api])
    post("/deck-info", DeckController, :deck_info)
    get("/deck-info/*deck", DeckController, :deck_info)
    get("/who-am-i", ApiController, :who_am_i)
    post("/dt/game", DeckTrackerController, :put_game)
    put("/dt/game", DeckTrackerController, :put_game)
    get("/cards/dust-free", CardsController, :dust_free)
    get("/cards/all", CardsController, :all)
    get("/cards/collectible", CardsController, :collectible)
    get("/cards/metadata", CardsController, :metadata)
  end

  scope "/admin", BackendWeb do
    pipe_through([:browser, :auth, :super_admin])
    live("/panel", AdminPanelLive)
    live("/super/playground", PlaygroundLive)
  end

  scope "/", BackendWeb do
    pipe_through([:browser, :auth])

    get("/arcticles/reveal/booms-incredible-inventions-mage", RevealController, :boom)
    get("/hs/article/:blog_id", HearthstoneController, :article)
    get("/battlefy/tournament/020fface81eb7119705c0df5:bla", PageController, :rick_astley)

    get("/leaderboard", LeaderboardController, :index)
    get("/leaderboard/player-stats", LeaderboardController, :player_stats)

    get(
      "/leaderboard/player-history/region/:region/period/:period/leaderboard_id/:leaderboard_id/player/:player",
      LeaderboardController,
      :player_history
    )

    get(
      "/leaderboard/rank-history/region/:region/period/:period/leaderboard_id/:leaderboard_id/rank/:rank",
      LeaderboardController,
      :rank_history
    )

    get(
      "/leaderboard/player-history/region/:region/season_id/:season_id/leaderboard_id/:leaderboard_id/player/:player",
      LeaderboardController,
      :player_history_old
    )

    get("/leaderboard/points", LeaderboardController, :points)

    live("/", FeedLive)
    get("/incubator", PageController, :incubator)
    get("/about", PageController, :about)
    get("/donate-follow", PageController, :donate_follow)
    get("/privacy", PageController, :privacy)

    get("/hdt-plugin", PageController, :hdt_plugin)

    get("/log", PageController, :log)
    put("/log", PageController, :log)
    post("/log", PageController, :log)

    get("/test", PageController, :test)

    get("/hs/patch-notes", HearthstoneController, :patch_notes)
    get("/hs/patchnotes", HearthstoneController, :patch_notes)

    live("/legacy-hsesports", LegacyHSEsportsLive)
    get("/legacy-hsesports/invited/:tour_stop", MastersTourController, :invited_players)
    get("/legacy-hseports/invited/", MastersTourController, :invited_players)
    get("/legacy-hsesports/qualifiers", MastersTourController, :qualifiers)
    get("/legacy-hsesports/mt/points", MastersTourController, :points)
    get("/legacy-hsesports/mt/earnings", MastersTourController, :earnings)
    get("/legacy-hsesports/mt/qualifier-stats/", MastersTourController, :qualifier_stats)

    get(
      "/legacy-hsesports/mt/qualifier-stats/:tour_stop",
      MastersTourController,
      :qualifier_stats
    )

    get("/mt/tour-stops", MastersTourController, :tour_stops)
    get("/legacy-hsesports/mt/stats", MastersTourController, :masters_tours_stats)
    get("/mtq/:mtq_num", MastersTourController, :qualifier_redirect)
    get("/mtq/:mtq_num/*rest", MastersTourController, :qualifier_redirect)

    get("/hdt-plugin/latest-version", DeckTrackerController, :hdt_plugin_latest_version)
    get("/hdt-plugin/latest", DeckTrackerController, :hdt_plugin_latest_file)
    get("/hdt-plugin/d0nkey.top plugin.dll", DeckTrackerController, :hdt_plugin_latest_file)

    get(
      "/battlefy/third-party-tournaments/stats/:stats_slug",
      BattlefyController,
      :organization_tournament_stats
    )

    get("/battlefy/third-party-tournaments", BattlefyController, :organization_tournaments)

    live("/battlefy/tournament/:tournament_id/match/:match_id", BattlefyMatchLive)
    live("/battlefy/tournament/:tournament_id/lineups", BattlefyTournamentDecksLive)
    live("/battlefy/tournament/:tournament_id/participants", BattlefyParticipantsLive)

    get("/profile/battlefy/tournament/:tournament_id", BattlefyController, :profile_tournament)
    get("/battlefy/tournament/:tournament_id", BattlefyController, :tournament)

    get(
      "/battlefy/tournament/:tournament_id/player/:team_name",
      BattlefyController,
      :tournament_player
    )

    get(
      "/battlefy/tournament/:tournament_id/future/:team_name",
      BattlefyController,
      :tournament_player
    )

    get(
      "/battlefy/tournament/:tournament_id/decks/:team_name",
      BattlefyController,
      :tournament_decks
    )

    get(
      "/battlefy/tournaments-stats/",
      BattlefyController,
      :tournaments_stats
    )

    get("/battlefy/user-tournaments/:slug", BattlefyController, :user_tournaments)

    get("/hsreplay/matchups", HSReplayController, :matchups)

    get("/discord/broadcasts", DiscordController, :broadcasts)

    # get "/discord/broadcast", DiscordController, :broadcast
    # post "/discord/broadcast", DiscordController, :broadcast

    get("/discord/broadcasts/:id/publish/:token", DiscordController, :view_publish)
    post("/discord/broadcasts/:id/publish/:token", DiscordController, :publish)

    get("/discord/broadcasts/:id/subscribe/:token", DiscordController, :view_subscribe)
    post("/discord/broadcasts/:id/subscribe/:token", DiscordController, :subscribe)

    get("/discord/create_broadcast", DiscordController, :create_broadcast)

    get("/player-profile/:battletag_full", PlayerController, :player_profile)

    get("/streamer-decks/twitch-login/:twitch_login", StreamingController, :streamers_decks)
    get("/streamer-decks", StreamingController, :streamer_decks)
    get("/streamer-instructions", StreamingController, :streamer_instructions)
    live("/streaming-now", StreamingNowLive)
    live("/youtube/bnet-chat/:video_id", YoutubeChatLive)

    live("/cards", CardsLive)
    live("/card/:card_id", CardLive)

    live("/deckbuilder", DeckBuilderLive)
    live("/deckviewer", DeckviewerLive)

    get("/stats/explanation", StatsController, :explanation)
    live("/esports", EsportsLive)
    live("/card-stats", CardStatsLive)
    live("/meta", MetaLive)
    live("/decks", DecksLive)
    live("/deck-sheets/:sheet_id", DeckSheetViewLive)
    live("/deck-sheets", DeckSheetsIndexLive)
    live("/replays", ReplaysLive)

    live("/archetype/:archetype", ArchetypeLive)

    live("/hcm-2022", HCM2022Live)
    live("/lineup-history/:source/:name", LineupHistoryLive)

    # get "/decks", PageController, :disabled
    live("/deck/*deck", DeckLive)
    live("/deck-tracker/*deck", DeckTrackerLive)

    get("/grandmasters/season/:season", GrandmastersController, :grandmasters_season)

    get("/who-am-i", AuthController, :who_am_i)
    get("/whoami", AuthController, :who_am_i)
    get("/login-welcome", AuthController, :login_welcome)
    get("/logout", AuthController, :logout)
    live("/feed", FeedLive)
    get("/empty/with-nav", EmptyController, :with_nav)
    get("/empty/without-nav", EmptyController, :without_nav)

    live("/fantasy", FantasyIndexLive)
    live("/fantasy/leagues/:league_id/draft", FantasyDraftLive)
    live("/fantasy/leagues/:league_id", FantasyLeagueLive)
    live("/fantasy/leagues/join/:join_code", JoinLeagueLive)

    get("/util/twitter/callback/reqtop100", TwitterController, :req_top100_callback)

    get("/discord-bot", SocialController, :discord_bot)
    get("/discord_bot", SocialController, :discord_bot)
    get("/discord", SocialController, :discord)
    get("/paypal", SocialController, :paypal)
    get("/twitch", SocialController, :twitch)
    get("/patreon", SocialController, :patreon)
    get("/twitter", SocialController, :twitter)
    get("/notion", SocialController, :notion)
    get("/liberapay", SocialController, :liberapay)

    live("/gm/lineups", GrandmastersLineup)
    live("/gm", GrandmastersLive)
    live("/gm/profile/:gm", GrandmasterProfileLive)

    live(
      "/tournament-lineups/:tournament_source/:tournament_id/popularity",
      TournamentLineupPopularityTableLive
    )

    live(
      "/tournament-lineups/:tournament_source/:tournament_id/stats",
      TournamentLineupArchetypeStatsTable
    )

    live("/tournament-lineups/:tournament_source/:tournament_id", TournamentLineups)

    live("/wc/2021", WC2021Live)
    live("/wc/2022", WC2022Live)
    live("/wc/2024/china-qualifiers", WC2024ChinaQualifiers)
    live("/seasonal/2022/summer", SummerChamps2022Live)

    live("/max/nations-2022", MaxNations2022Live)
    live("/max/nations-2022/nation/:nation", MaxNations2022NationLive)
    live("/max/nations-2022/player/:player", MaxNations2022PlayerLive)

    live("/my-replays", MyReplaysLive)
    live("/my-decks", MyDecksLive)

    live("/groups/:group_id/decks", GroupDecksLive)
    live("/groups/:group_id/replays", GroupReplaysLive)
    live("/groups/:group_id", GroupLive)
    live("/groups", MyGroupsLive)
    live("/my-groups", MyGroupsLive)

    live("/player/:player_btag/decks", PlayerDecksLive)
    live("/player/:player_btag/replays", PlayerReplaysLive)

lib/backend/masters_tour/battlefy_communictor.ex
defmodule Backend.MastersTour.BattlefyCommunicator do
  @type qualifier :: %{
          name: String.t() | nil,
          start_time: NaiveDateTime.t(),
          slug: String.t(),
          region: String.t(),
          id: String.t()
        }
  @callback get_masters_qualifiers() :: [qualifier]
  @callback get_masters_qualifiers(NaiveDateTime.t(), NaiveDateTime.t()) :: [qualifier]

  @type invited_player :: %{
          battletag_full: String.t(),
          reason: String.t(),
          type: String.t(),
          tour_stop: String.t(),
          upstream_time: NaiveDateTime.t(),
          tournament_slug: String.t() | nil,
          tournament_id: String.t() | nil
        }
  @callback get_invited_players(tour_stop: String.t() | nil) :: [invited_player]
end

lib/backend/masters_tour/invited_player.ex
defmodule Backend.MastersTour.InvitedPlayer do
  @moduledoc false
  use Ecto.Schema
  import Ecto.Changeset
  @type source :: :official | :unofficial | :other_ladder

  schema "invited_player" do
    field :battletag_full, :string
    field :tour_stop, :string
    field :type, :string
    field :reason, :string
    field :upstream_time, :utc_datetime
    field :tournament_slug, :string
    field :tournament_id, :string
    field :official, :boolean, default: true
    timestamps()
  end

  @doc false
  def changeset(invited, attrs) do
    invited
    |> cast(
      attrs,
      [
        :battletag_full,
        :tour_stop,
        :type,
        :reason,
        :upstream_time,
        :tournament_slug,
        :official,
        :tournament_id
      ]
    )
    |> update_change(:battletag_full, &String.trim/1)
    |> validate_required([:battletag_full, :tour_stop, :upstream_time])
  end

  @spec shorten_battletag(Backend.Blizzard.battletag()) :: String.t()
  def shorten_battletag(battletag_full) do
    battletag_full
    # some in the db still have it, meh, don't feel like changing it
    |> String.trim()
    |> String.splitter("#")
    |> Enum.at(0)
    |> to_string()
  end

  @spec uniq_string(InvitedPlayer.t()) :: String.t()
  def uniq_string(%{battletag_full: bt, tour_stop: ts, official: o}) do
    uniq_string(bt, ts, o)
  end

  @spec uniq_string(String.t(), Backend.Blizzard.tour_stop(), boolean) :: String.t()
  @spec uniq_string(String.t(), Backend.Blizzard.tour_stop()) :: String.t()
  def uniq_string(battletag_full, tour_stop, official \\ true) do
    String.trim(battletag_full) <> to_string(tour_stop) <> to_string(official)
  end

  @doc """
  Uniques the players for each tour while prioritizing by source
  """
  @spec prioritize([InvitedPlayer.t()]) :: [InvitedPlayer.t()]
  def prioritize(invited_players) do
    prioritize(invited_players, &Util.id/1)
  end

  def prioritize(invited_players, transform_battletag) do
    sort = fn first, second -> first.official && !second.official end

    invited_players
    |> Enum.group_by(fn ip -> ip.tour_stop end)
    |> Enum.flat_map(fn {_, tsg} ->
      tsg
      |> Enum.group_by(fn ip -> transform_battletag.(ip.battletag_full) end)
      |> Enum.map(fn {_, ips} ->
        ips
        |> Enum.sort(sort)
        |> Enum.at(0)
      end)
    end)
  end

  @doc """
  Uniques the players for each tour while prioritizing by source
  """
  @spec source(InvitedPlayer.t()) :: source
  def source(%__MODULE__{official: official}) do
    if official do
      :official
    else
      :unofficial
    end
  end
end

lib/backend/masters_tour/player_nationality.ex
defmodule Backend.MastersTour.PlayerNationality do
  @moduledoc false
  use Ecto.Schema
  import Ecto.Changeset
  @required [:mt_battletag_full, :tour_stop, :nationality]
  @optional [:actual_battletag_full, :twitch]
  schema "mt_player_nationality" do
    field :mt_battletag_full, :string
    field :tour_stop, :string
    field :nationality, :string
    field :actual_battletag_full, :string, default: nil
    field :twitch, :string, default: nil
    timestamps()
  end

  @doc false
  def changeset(cs, attrs) do
    cs
    |> cast(attrs, @required ++ @optional)
    |> update_change(:actual_battletag_full, &String.trim/1)
    |> update_change(:mt_battletag_full, &String.trim/1)
    |> validate_required(@required)
  end
end

lib/backend/masters_tour/qualifier.ex
defmodule Backend.MastersTour.Qualifier do
  @moduledoc false
  use Ecto.Schema
  import Ecto.Changeset
  alias Backend.MastersTour.Qualifier.Standings
  @type type :: :single_elimination

  @non_embed_attrs [
    :tour_stop,
    :start_time,
    :end_time,
    :region,
    :tournament_id,
    :tournament_slug,
    :winner,
    :type
  ]
  @embed_attrs [:standings]
  @all_attrs @non_embed_attrs ++ @embed_attrs
  schema "qualifier" do
    field :tour_stop, :string
    field :start_time, :utc_datetime
    field :end_time, :utc_datetime
    field :region, :string
    field :tournament_id, :string
    field :tournament_slug, :string
    field :winner, :string
    field :type, :string
    embeds_many(:standings, Standings)
    timestamps()
  end

  @doc false
  def changeset(qualifier = %__MODULE__{tour_stop: nil}, attrs) do
    qualifier
    |> cast(attrs, @non_embed_attrs)
    |> cast_embed(:standings)
    |> validate_required(@all_attrs)
  end


  def num(slug) when is_binary(slug) do
    slug
    |> String.split("-")
    |> Enum.at(-1)
    |> Util.to_int(nil)
  end
  def num(%{slug: slug}), do: num(slug)
  def num(%{tournament_slug: tournament_slug}), do: num(tournament_slug)
  def num(_), do: nil

end

defmodule Backend.MastersTour.Qualifier.Standings do
  use Ecto.Schema
  import Ecto.Changeset
  @all_attrs [:battletag_full, :wins, :losses, :position]
  @primary_key {:battletag_full, :string, autogenerate: false}
  embedded_schema do
    field :wins, :integer
    field :losses, :integer
    field :position, :integer
  end

  @doc false
  def changeset(standings, attrs) do
    standings
    |> cast(attrs, @all_attrs)
    |> validate_required(@all_attrs)
  end

  @spec no_result?(Standings.t()) :: boolean
  def no_result?(standings), do: standings.wins + standings.losses < 1

  @spec no_result(Standings.t()) :: integer
  def no_result(standings), do: if(no_result?(standings), do: 1, else: 0)

  @spec only_losses?(Standings.t()) :: boolean
  def only_losses?(standings), do: standings.wins < 1 && standings.losses > 0

  @spec only_losses(Standings.t()) :: integer
  def only_losses(standings), do: if(only_losses?(standings), do: 1, else: 0)

  @spec won?(Standings.t()) :: boolean
  def won?(standings), do: standings.position == 1
  @spec won(Standings.t()) :: integer
  def won(standings), do: if(won?(standings), do: 1, else: 0)

  @spec top8?(Standings.t()) :: boolean
  def top8?(standings), do: standings.position < 9

  @spec top8(Standings.t()) :: integer
  def top8(standings), do: if(top8?(standings), do: 1, else: 0)

  @spec top16?(Standings.t()) :: boolean
  def top16?(standings), do: standings.position < 17

  @spec top16(Standings.t()) :: integer
  def top16(standings), do: if(top16?(standings), do: 1, else: 0)
end

lib/backend_web/templates/masters_tour/earnings.html.eex
<div class="title is-2"><%=@title%></div>
<div id="nitropay-below-title-leaderboard"></div><br>
<%= render_dropdowns @dropdowns %>
<table class="table is-striped is-fullwidth is-narrow">
    <thead>
        <tr>
            <%= @headers %>
        </tr>
    </thead>
    <tbody>
        <%= for row <- @rows do %>
            <%= row %>
        <% end %>
    </tbody>
</table>

lib/backend_web/templates/masters_tour/earnings.html.heex
<div class="title is-2"><%=@title%></div>
<FunctionComponents.Ads.below_title/>
<%= render_dropdowns @dropdowns %>
<table class="table is-striped is-fullwidth is-narrow">
    <thead>
        <tr>
            <%= @headers %>
        </tr>
    </thead>
    <tbody>
        <%= for row <- @rows do %>
            <%= row %>
        <% end %>
    </tbody>
</table>

lib/backend_web/templates/masters_tour/invited_players.html.heex
<div class="title is-2">Invited Players</div>
<div class="subtitle is-6">
    <a target="_blank" href="https://battlefy.com/hsesports/invites">
        Official List
    </a>
    <%= if @latest do %>
        | <span>Latest: </span><%=render_datetime(@latest)%>
    <% end %>
</div>
<FunctionComponents.Ads.below_title/>
<%= render_dropdowns(@dropdowns) %>

<table class="table is-striped is-fullwidth is-narrow">
    <thead>
        <tr>
            <th>Battletag</th>
            <th>Reason</th>
            <th>Source</th>
            <th>Invited At</th>
        </tr>
    </thead>
    <tbody>
    <%= for player = %{reason: reason, battletag: battletag, invited_at: invited_at, official: official, country: country}
     <-
    @invited_players do %>
        <tr>
        <td>
            <%= if country do %>
                <%= country_flag(country, battletag) %>
            <% end %>
            <%= render_player_icon(battletag) %>
            <a href={"#{player.profile_link}"}> <%= battletag %> </a>
        </td>
        <td>
            <%= if player.tournament_link do %>
                <a href={"#{player.tournament_link}"}> <%= reason %> </a>
            <% else %>
                <%= reason %>
            <% end %> </td>
        <td>
            <%= if official do %>
                <div class="tag is-info">Official</div>
            <% else %>
                <div class="tag is-warning">Unofficial</div>
            <% end %> </td>
        <td><%= render_datetime invited_at%></td>
        </tr>
    <% end %>
    </tbody>
</table>

lib/backend_web/templates/masters_tour/qualifier_stats.html.heex
<div class="title is-2"><%= @title %></div>
<div class="subtitle is-6">
    <%= @subtitle %>
    <%= if @has_winrate_qual do %>
        | <a href="https://twitter.com/Abar_HS/status/1426893531281383428" target="_blank">Tiebreakers</a> - h2h not implemented here
        | <a href="https://hearthstone.doc-x.net/" target="_blank">Official Top 50</a>
    <% end %>
</div>
<FunctionComponents.Ads.below_title/>


<%= form_for @conn, Routes.masters_tour_path(@conn, :qualifier_stats, @period, @conn.query_params),
[method: :get], fn
f-> %>
    <%= for {key, value} when is_binary(value) or is_integer(value) <- @conn.query_params do %>
        <input name={"#{ key }"} type="hidden" value={"#{ value }"}>
    <% end %>
    <%= @prev_button %>
    <%= @next_button %>
    <%= render_dropdowns @dropdowns %>
    <%= render_multiselect_dropdown %{
        form: f,
        title: "Columns",
        options: @columns_options,
        selected_first: false,
        attr: "columns"
    } %>
    <%= render_countries_multiselect_dropdown(f, @selected_countries) %>
<% end %>
<table class="table is-striped is-fullwidth is-narrow">
    <thead>
        <tr>
            <%= for hd <- @headers do %>
                <th> <%= hd %> </th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <%= for row <- @rows do %>
            <tr>
                <%= for cell <- row do %>
                    <td> <%= cell %> </td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

lib/backend_web/templates/masters_tour/qualifiers.html.heex
<div class="title is-2">Qualifiers</div>
<div class="subtitle is-6">
    <a href="https://battlefy.com/hsesports#faq" target="_blank">
        Help / Official Site
    </a>

    | <a href={"#{Routes.masters_tour_path(@conn, :qualifier_stats) }"}>
        Stats
    </a>
    | <a href="http://offcurve.com/masterstour">
        Offcurve (deck stats)
    </a>
</div>
<FunctionComponents.Ads.below_title/>
<a class="button icon is-link" href={"#{ @before_link }"}>
  <HeroIcons.chevron_left />
</a>
<a class="button icon is-link" href={"#{ @after_link }"}>
  <HeroIcons.chevron_right />
</a>
<FunctionComponents.Dropdown.menu title="Select Range">
    <%= for %{display: display, link: link} <- @dropdown_links do %>
        <FunctionComponents.Dropdown.item href={"#{ link }"}>
            <%=display%>
        </FunctionComponents.Dropdown.item>
    <% end %>
</FunctionComponents.Dropdown.menu>
<FunctionComponents.Dropdown.menu title={@region || "Filter Region"}>
    <%= for %{display: display, link: link} <- @region_links do %>
        <FunctionComponents.Dropdown.item href={"#{ link }"}>
            <%=display%>
        </FunctionComponents.Dropdown.item>
    <% end %>
</FunctionComponents.Dropdown.menu>
<table class="table is-striped is-fullwidth is-narrow">
    <thead>
        <tr>
            <th>Name</th>
            <th>Winner</th>
            <th>Start Time</th>
            <th>Region</th>
            <%= if @show_signed_up do %>
                <th>Signed Up</th>
            <% end %>
            <th>Standings</th>
        </tr>
    </thead>
    <tbody>
    <%= for t = %{region: region, start_time: start_time, name: name, link: link, standings_link: standings_link, signed_up: signed_up} <- @qualifiers do %>
        <tr>
            <td>
                <a class="is-link" href={"#{ link }"}>
                    <%= name %>
                </a>
            </td>
            <td><%= t.winner %></td>
            <td><%= render_datetime start_time %></td>
            <td><%= region %></td>
            <%= if @show_signed_up do %>
                <td>
                    <Components.Helper.checkmark show={signed_up} />
                </td>
            <% end %>
            <td>
                <%= if t |> Backend.Battlefy.Tournament.has_bracket() do %>
                    <a class="is-link" href={"#{ standings_link }"}>
                        standings
                    </a>
                <% end %>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>

lib/backend_web/templates/masters_tour/tour_stops.html.eex
<div class="title is-2">Tour Stops</div>
<div id="nitropay-below-title-leaderboard"></div><br>
<%= render(BackendWeb.BattlefyView, "tournament_table.html", conn: @conn, raw: @raw, slug: @slug) %>

lib/backend_web/templates/masters_tour/tour_stops.html.heex
<div class="title is-2">Tour Stops</div>
<FunctionComponents.Ads.below_title/>
<%= render(BackendWeb.BattlefyView, "tournament_table.html", conn: @conn, raw: @raw, slug: @slug) %>